### ISSUE TITLE
Exception with logging compat when format arg is dict with non-string keys

### ISSUE THREAD

**Issue by gmacon** [getlogbook/logbook#228]
I think this is related to, but distinct from #151, and I'm not sure exactly why this happens.

Example:
```python
import logging
import logbook
import logbook.compat

logbook.compat.redirect_logging()
logbook.StderrHandler().push_application()

logging.debug('A dict with non-string keys: %r', {0: 'foo'})
```

Output:
```
Traceback (most recent call last):
  File "pyenv/logbook/logbook/base.py", line 532, in message
    **self.kwargs)
TypeError: _format_message() keywords must be strings

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyenv/logbook/logbook/handlers.py", line 213, in handle
    self.emit(record)
  File "pyenv/logbook/logbook/handlers.py", line 580, in emit
    msg = self.format(record)
  File "pyenv/logbook/logbook/handlers.py", line 192, in format
    return self.formatter(record, self)
  File "pyenv/logbook/logbook/handlers.py", line 384, in __call__
    line = self.format_record(record, handler)
  File "pyenv/logbook/logbook/handlers.py", line 368, in format_record
    return self._formatter.format(record=record, handler=handler)
  File "pyenv/logbook/logbook/helpers.py", line 281, in __get__
    value = self.func(obj)
  File "pyenv/logbook/logbook/base.py", line 567, in message
    raise TypeError(errormsg)
TypeError: Could not format message with provided arguments: _format_message() keywords must be strings
  msg='A dict with non-string keys: %r'
  args=()
  kwargs={0: 'foo'}.
Happened in file logbook_intdict_repro.py, line 10
Logged from file logbook_intdict_repro.py, line 10
```

This is logbook on master (f158adbf6e9edd73903650d2453c0ba58840e1e1) and Python 3.5.2.

**Comment by vmalloc** [comment]
Unfortunately this cannot be easily fixed in Logbook because the culprit is an ugly hack in Python's `logging` library which can be found here: https://github.com/python/cpython/blob/master/Lib/logging/__init__.py#L272.

`logging` allows passing a single dictionary argument and in that case treats it as a bunch of keyword arguments to formatting. Logbook understands this and handles it well, but in that mode keywords can't be non-strings...

My suggestion is either pass a second, dummy argument that would undo this tweak:
```
logging.debug('A dict with non-string keys: %r', {0: 'foo'}, None)
```

Or just move the `repr` out of the log record:
```
logging.debug('A dict with non-string keys: %s', repr({0: 'foo'}))
```

Or, even better yet, just migrate your code to use Logbook...

**Comment by gmacon** [comment]
Oh, wow. I think that would have taken me a while to figure out. Thanks for explaining it.
