### ISSUE TITLE
AttributeError on multiple submodule

### ISSUE THREAD

**Issue by MayukhSobo** [getlogbook/logbook#269]
I am getting ```AttributeError``` on multiple imports specially the imports like

 - `logbook.notifiers`
 - `logbook.more`

![image](https://user-images.githubusercontent.com/8527634/43400854-6ae56e14-942c-11e8-8a39-a52d1df97b3f.png)

![image](https://user-images.githubusercontent.com/8527634/43400927-96963ba6-942c-11e8-9dbb-b7d33beaf409.png)

I went ahead checking your `__init__.py` file and didn't see any entry for these modules

**Comment by vmalloc** [comment]
The good practice is to import those if you need them. It is not a guarantee in Python packaging that a package should import all its sub-packages in its toplevel namespace...

**Comment by vmalloc** [comment]
Just to be clear - that means that in your code you should:
```
from logbook.notifiers import ...
```
or
```
from logbook import notifiers
```

**Comment by MayukhSobo** [comment]
Sorry for a little delayed response but I can import it after restarting my system. But now I am getting the following error

```python
Traceback (most recent call last):
  File "/Users/mayukhsarkar/Documents/Codes/ACE/venv/lib/python3.6/site-packages/logbook/notifiers.py", line 75, in __init__
    import Growl
ModuleNotFoundError: No module named 'Growl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mayukhsarkar/Library/Preferences/PyCharmCE2018.2/scratches/scratch.py", line 3, in <module>
    create_notification_handler()
  File "/Users/mayukhsarkar/Documents/Codes/ACE/venv/lib/python3.6/site-packages/logbook/notifiers.py", line 33, in create_notification_handler
    return GrowlHandler(application_name, level=level, icon=icon)
  File "/Users/mayukhsarkar/Documents/Codes/ACE/venv/lib/python3.6/site-packages/logbook/notifiers.py", line 78, in __init__
    raise RuntimeError('The growl module is not available.  You have '
RuntimeError: The growl module is not available.  You have to install either growl-py or py-Growl to use the GrowlHandler.
```

**Comment by vmalloc** [comment]
@MayukhSobo IIRC the `notifiers` module is intended for cases where you have Growl installed...

**Comment by MayukhSobo** [comment]
@vmalloc Yes but two things here.

 First, installing Logbook should have installed all its dependencies which it didn't
 Second, I did ```pip install Growl``` but it is not working after that too.

**Comment by vmalloc** [comment]
Growl is not a dependency of Logbook. It doesn't make sense forcing such an unrelated package by default. The right thing is to use extras, and that we should probably do. Until then the right thing to do is include Growl in your own requirements if you require it. Logbook should work with or without it until it requires a feature provided by it.

Secondly, it's strange that `pip install Growl` doesn't solve it... Are you able to import the required module manually after installing it?

**Comment by MayukhSobo** [comment]
No I am not able to do it..Have a look
![image](https://user-images.githubusercontent.com/8527634/43503270-40198b9c-957c-11e8-8762-9581e4340275.png)

![image](https://user-images.githubusercontent.com/8527634/43503358-9e306426-957c-11e8-9b80-1c85f118b150.png)

**Comment by vmalloc** [comment]
Yup, this seems broken... I don't think it ever worked :-(

If you can provide a PR that fixes it that would be very welcome.

**Comment by MayukhSobo** [comment]
Okay....I seemed to have figured out the problem..

**Comment by vmalloc** [comment]
@MayukhSobo what is it? I don't see how that import can work in today's `Growl`...

**Comment by MayukhSobo** [comment]
Actually can you point out where did you see the growl package? If it is this [link](https://pypi.org/project/Growl/) then the problem is that it has to be installed and imported with `growl` with small g...I did that and now it is giving me a different error, but at least not Module Not found.

PS: Please mention if you have user some other package.

**Comment by vmalloc** [comment]
Yes the problem is the code is attempting to import a name not provided by the specific package known as `Growl`. This could be a historic mistake or a breakage on behalf of the folks maintaining `Growl`, as this is very old and not very widely used apparently...

**Comment by MayukhSobo** [comment]
I was wondering if you can move to a better notification system as the current one using Growl is pretty old and requires a paid Growl service.
